/**
 * One-time seeding route — hit POST /api/seed-facts to create & populate
 * the elephant_facts table.  Requires the SUPABASE_SERVICE_ROLE_KEY env var.
 * Delete or gate this route after seeding.
 */
import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";

export const runtime = "edge";

const FACTS: Array<[number, string, string]> = [
  [1,"Size, Weight & Physical Dimensions","African bush elephants are the largest land animals on Earth, weighing up to 14,000 pounds (6,350 kg)."],
  [2,"Size, Weight & Physical Dimensions","The largest elephant ever recorded stood 3.96 meters (13 feet) tall at the shoulder and weighed a staggering 10,400 kg (22,928 lbs)."],
  [3,"Size, Weight & Physical Dimensions","A newborn elephant weighs about 200 pounds (90 kg) at birth — heavier than most adult humans."],
  [4,"Size, Weight & Physical Dimensions","Some newborn African bush elephant calves have weighed as much as 120 kg (264 lbs)."],
  [5,"Size, Weight & Physical Dimensions","African elephants stand 8–13 feet (2.4–4 m) tall at the shoulder."],
  [6,"Size, Weight & Physical Dimensions","Male African bush elephants can weigh up to 6 tonnes (6,000 kg / 13,200 lbs)."],
  [7,"Size, Weight & Physical Dimensions","Female African bush elephants are about 60 cm shorter and roughly half the weight of males."],
  [8,"Size, Weight & Physical Dimensions","Asian elephants weigh roughly 4,000 kg (4.4 tonnes) with a shoulder height of up to 2.75 m."],
  [9,"Size, Weight & Physical Dimensions","African forest elephants, the smallest of the three species, weigh around 2,000 kg (2.2 tonnes) and stand 2.2 m tall."],
  [10,"Size, Weight & Physical Dimensions","An elephant's skull is six inches thick in some places, designed to withstand head-to-head collisions."],
  [11,"Size, Weight & Physical Dimensions","Despite the enormous skull, honeycomb-like air spaces inside make it relatively lightweight."],
  [12,"Size, Weight & Physical Dimensions","An adult male elephant's heart weighs 12–21 kg (26–46 lbs)."],
  [13,"Size, Weight & Physical Dimensions","An elephant is roughly twice the size of a hippopotamus and about 4 times the size of a rhinoceros."],
  [14,"Size, Weight & Physical Dimensions","One African elephant weighs about as much as 130 adult human men (based on 70 kg average)."],
  [15,"Size, Weight & Physical Dimensions","An elephant weighs more than two large SUVs combined."],
  [16,"Size, Weight & Physical Dimensions","A fully grown elephant's tongue weighs about 12 kg (26 lbs)."],
  [17,"Size, Weight & Physical Dimensions","The elephant's tail can grow up to 4 feet long."],
  [18,"Size, Weight & Physical Dimensions","An elephant's liver weighs approximately 18 kg (40 lbs)."],
  [19,"Size, Weight & Physical Dimensions","Elephant intestines can reach up to 19 meters (62 feet) in length."],
  [20,"Size, Weight & Physical Dimensions","An adult elephant's skin can be up to one inch (2.5 cm) thick in some places."],
  [21,"The Trunk","An elephant's trunk contains over 40,000 individual muscles (some sources cite up to 150,000 muscle fascicles)."],
  [22,"The Trunk","The entire human body has only about 600 muscles — an elephant's trunk has roughly 67 times more than our whole body."],
  [23,"The Trunk","Despite weighing up to 400 pounds (181 kg), the trunk is nimble enough to pick up a single grain of rice."],
  [24,"The Trunk","An elephant's trunk is 6–8 feet (1.8–2.4 m) long in adults."],
  [25,"The Trunk","The trunk has no bones and no cartilage — it is a muscular hydrostat, like a human tongue."],
  [26,"The Trunk","African elephants have two 'fingers' at the tip of their trunk; Asian elephants have only one."],
  [27,"The Trunk","An elephant can suction up to 10 liters (2.6 gallons) of water into its trunk at once."],
  [28,"The Trunk","Elephants can use their trunks as snorkels when swimming underwater."],
  [29,"The Trunk","Baby elephants are born with little trunk control and must learn to use them over several months."],
  [30,"The Trunk","Baby elephants sometimes suck their trunks for comfort, just as human babies suck their thumbs."],
  [31,"The Trunk","By about 4 months old, calves learn to use their trunks to eat and drink."],
  [32,"The Trunk","An elephant's trunk can lift over 550 pounds (250 kg)."],
  [33,"The Trunk","The trunk can reach branches 20 feet (6 m) high."],
  [34,"The Trunk","The trunk is a combination of the nose and upper lip, with nostrils running along the interior."],
  [35,"The Trunk","Elephants use their trunks for smelling, touching, grasping, breathing, creating sounds, socializing, and drinking."],
  [36,"The Trunk","The trunk is innervated by two proboscidean nerves, making it extremely sensitive — it can detect the gentlest touch."],
  [37,"The Trunk","Elephants can crack a peanut open with their trunk, blow away the shell, and eat the kernel."],
  [38,"The Trunk","Trunks were formed over millions of years from the fusion and extension of the nose and upper lip of ancient elephant ancestors."],
  [39,"The Trunk","The trunk's sensory hairs at the tip can detect shape, texture, and temperature of objects."],
  [40,"Tusks & Teeth","Elephant tusks are enlarged incisor teeth made of ivory (dentine)."],
  [41,"Tusks & Teeth","Tusks grow throughout an elephant's entire life and can reach lengths of over 10 feet (3 m)."],
  [42,"Tusks & Teeth","Up to one-third of a tusk is hidden inside the elephant's skull."],
  [43,"Tusks & Teeth","Both male and female African elephants have tusks, but only male Asian elephants typically grow them (and not all males)."],
  [44,"Tusks & Teeth","Some male Asian elephants are tuskless and are known as 'muknas'."],
  [45,"Tusks & Teeth","Elephants have a 'master tusk' — just like humans are right- or left-handed, they favor one tusk over the other."],
  [46,"Tusks & Teeth","The favored tusk often appears more worn down from heavier use."],
  [47,"Tusks & Teeth","Elephants have only four teeth at a time: one upper and one lower on each side."],
  [48,"Tusks & Teeth","They get six sets of cheek teeth (molars) in their lifetime, but they do not erupt all at once."],
  [49,"Tusks & Teeth","New teeth develop from behind and slowly push forward as worn teeth fragment and fall out or are swallowed."],
  [50,"Tusks & Teeth","Each successive set of molars is longer, wider, and heavier than the last."],
  [51,"Tusks & Teeth","The last molars can measure nearly 40 cm (16 inches) long and weigh more than 5 kg (11 lbs)."],
  [52,"Tusks & Teeth","After about 60 years of age, only the last four molars remain — tooth loss can cause starvation and death."],
  [53,"Tusks & Teeth","Tusks are used for digging, foraging, fighting, stripping bark, and protecting the sensitive trunk."],
  [54,"Tusks & Teeth","Tusk size and shape are genetically inherited."],
  [55,"Tusks & Teeth","The average tusk size of African elephants has halved in the last century due to poaching removing big-tusked genes from the gene pool."],
  [56,"Tusks & Teeth","An increasing number of African elephants are now being born without tusks due to evolutionary pressure from poaching."],
  [57,"Brain & Intelligence","The elephant brain weighs 10–12 pounds (4.5–5.4 kg) — the largest of any land animal."],
  [58,"Brain & Intelligence","For comparison, the human brain weighs about 3 pounds (1.4 kg)."],
  [59,"Brain & Intelligence","The elephant's cerebral cortex has the greatest weight, mass, and volume of all land mammals."],
  [60,"Brain & Intelligence","Elephants have a highly convoluted neocortex (more brain folds), a trait shared only by humans, apes, and some dolphins."],
  [61,"Brain & Intelligence","Elephants possess spindle neurons — specialized brain cells involved in processing emotions and social interaction, found only in humans, great apes, and elephants."],
  [62,"Brain & Intelligence","Elephants have a more developed hippocampus than any other animal (including humans), explaining their extraordinary memory."],
  [63,"Brain & Intelligence","Most mammals are born with 90% of their adult brain weight, but humans are born with 28% and elephants with only 35% — meaning they must learn most survival skills."],
  [64,"Brain & Intelligence","Elephants can pass the mirror test, recognizing themselves in a reflection — a sign of self-awareness shared only with humans, great apes, and dolphins."],
  [65,"Brain & Intelligence","In a famous study, an Asian elephant named Happy repeatedly touched an 'X' painted on her forehead while looking in a mirror."],
  [66,"Brain & Intelligence","Asian elephants can count — they can distinguish between pictures showing different numbers of fruit even when fruit sizes vary."],
  [67,"Brain & Intelligence","Elephants can distinguish between buckets containing different numbers of sunflower seeds just by sniffing them."],
  [68,"Brain & Intelligence","There are documented cases of a blind elephant successfully leading a herd — leadership does not depend on sight."],
  [69,"Brain & Intelligence","Elephants can learn through watching and mimicking other elephants."],
  [70,"Brain & Intelligence","An elephant's large temporal lobes are associated with memory storage, explaining their ability to follow migratory paths for decades."],
  [71,"Senses","African elephants have the best sense of smell in the animal kingdom — with about 2,000 genes dedicated to smell (humans have around 400)."],
  [72,"Senses","Elephants can smell water up to 12 miles (19.2 km) away."],
  [73,"Senses","An elephant's eyes are about 1.5 inches in diameter, only slightly larger than a human's 1-inch eyes."],
  [74,"Senses","Elephants have dichromatic vision — they see blues and yellows but cannot distinguish reds and greens (similar to color-blind humans)."],
  [75,"Senses","Elephants are somewhat nearsighted with a visual range of only about 30 feet."],
  [76,"Senses","At night elephants are most sensitive to violet light, allowing them to travel in near-darkness."],
  [77,"Senses","Elephant eyes come in colors including dark brown, honey, gray, blue-gray, gold, green, and yellow — and one eye can be a different color than the other."],
  [78,"Senses","Elephants have a third eyelid that moves horizontally to protect and moisten the eye during bathing or dusting."],
  [79,"Senses","Their eyelashes can grow up to 5 inches (13 cm) long."],
  [80,"Senses","Elephants can detect seismic vibrations through their feet using pacinian corpuscles in the soles."],
  [81,"Senses","Scientists believe elephants' seismic sensitivity helped many survive the 2004 Asian tsunami — they fled to higher ground before the waves hit."],
  [82,"Senses","Elephants can feel the vibrations of other herds up to 20 miles (32 km) away through the ground."],
  [83,"Communication & Sound","Elephants can make over 25 different sounds, each with its own meaning."],
  [84,"Communication & Sound","Elephants can produce sounds across 10 octaves — an extraordinary vocal range."],
  [85,"Communication & Sound","They communicate mostly through low-frequency rumbling sounds below the threshold of human hearing (infrasound)."],
  [86,"Communication & Sound","These infrasonic calls (5–24 hertz) can be heard by other elephants over 6 miles (10 km) away."],
  [87,"Communication & Sound","Under ideal conditions, their hearing range extends to 10 km (6.2 miles)."],
  [88,"Communication & Sound","Infrasonic sound waves travel through both air and ground, and elephants detect them as seismic waves through their feet."],
  [89,"Communication & Sound","Elephants have only 5 bones in their hyoid apparatus (vs. 9 in most mammals), allowing their larynx freedom to produce low-frequency rumbles."],
  [90,"Communication & Sound","A unique pharyngeal pouch behind the tongue serves as a resonating chamber for infrasound calls."],
  [91,"Communication & Sound","Elephants can also make sounds by beating their trunk on the ground, trees, or their own tusks."],
  [92,"Communication & Sound","They can produce growls, snorts, roars, trumpets, barks, and cries — each with distinct meanings."],
  [93,"Communication & Sound","Elephants can judge the distance of another elephant based on the pitch of its call — higher tones fade first over distance."],
  [94,"Communication & Sound","Rumbling sounds were initially thought to be from intestinal activity, but are now known to be produced by the voice box (larynx)."],
  [95,"Communication & Sound","A bull elephant in musth makes a characteristic rumbling sound that signals his aggressive state."],
  [96,"Communication & Sound","Elephants inhale and exhale an average of 310 liters of air per minute."],
  [97,"Social Behavior & Family Life","Elephant herds are matriarchal — led by the oldest and wisest female."],
  [98,"Social Behavior & Family Life","Herds typically consist of 6–20 elephants, though much larger gatherings have been observed."],
  [99,"Social Behavior & Family Life","Female elephants stay with the same herd their entire lives."],
  [100,"Social Behavior & Family Life","Males leave the herd at 12–15 years old and either join 'bachelor' herds or live alone."],
  [101,"Social Behavior & Family Life","Male and female herds migrate separately."],
  [102,"Social Behavior & Family Life","Elephants are among the world's most social animals."],
  [103,"Social Behavior & Family Life","The matriarch holds decades of knowledge about water sources, migration routes, and predator threats."],
  [104,"Social Behavior & Family Life","When herds meet, elephants greet each other with trunk-shaking — comparable to a human handshake."],
  [105,"Social Behavior & Family Life","Upon reuniting with old friends, elephants engage in joyous greeting ceremonies — spinning in circles, flapping ears, and trumpeting."],
  [106,"Social Behavior & Family Life","Elephants recognize each other after years and years of separation."],
  [107,"Social Behavior & Family Life","Elephants form all-female groups of mothers, daughters, sisters, aunts, and cousins — all caring for each other's young."],
  [108,"Social Behavior & Family Life","When a calf is born, aunts, sisters, and cousins all help care for the newborn."],
  [109,"Social Behavior & Family Life","All females in the herd learn essential calf-rearing lessons through this cooperative care."],
  [110,"Social Behavior & Family Life","Elephants may stand by the body of a dead relative for hours or even days, gently touching the bones."],
  [111,"Social Behavior & Family Life","Elephants have been documented visiting the bones of deceased elephants and spending time touching or even partially burying them."],
  [112,"Emotions, Grief & Empathy","Researchers have documented elephants displaying grief, compassion, joy, playfulness, and humor."],
  [113,"Emotions, Grief & Empathy","Elephants have been known to rescue trapped dogs and even attempt to bury deceased humans."],
  [114,"Emotions, Grief & Empathy","After an elephant trampled a woman and her child to death, it was observed covering their bodies with leaves and twigs — suggesting awareness of what it had done."],
  [115,"Emotions, Grief & Empathy","When Elephant Whisperer Lawrence Anthony died in 2012, a herd of wild elephants he had worked with traveled to his house and stood outside for two days to mourn him."],
  [116,"Emotions, Grief & Empathy","Elephants are one of the few animals known to mourn their dead across extended periods."],
  [117,"Emotions, Grief & Empathy","Elephants can harbor grudges — they remember individuals who harmed them and may retaliate years later."],
  [118,"Emotions, Grief & Empathy","They show compassion by helping injured herd members, supporting them with their trunks."],
  [119,"Emotions, Grief & Empathy","Elephants have been observed covering deceased elephants with dirt and vegetation in a form of burial."],
  [120,"Emotions, Grief & Empathy","They express joy through spinning, ear-flapping, trumpeting, and trunk-entwining."],
  [121,"Emotions, Grief & Empathy","Elephants can show empathy toward other species, including rescuing animals in distress."],
  [122,"Reproduction & Life Cycle","Elephants have the longest gestation period of any land animal — 22 months for African elephants and 18–22 months for Asian elephants."],
  [123,"Reproduction & Life Cycle","Female elephants can have babies until about 50 years old."],
  [124,"Reproduction & Life Cycle","They typically give birth once every 2.5 to 4 years (or once every 5 years in some populations)."],
  [125,"Reproduction & Life Cycle","A female elephant will typically give birth only 2–3 times per decade."],
  [126,"Reproduction & Life Cycle","Young elephants may suckle for several years."],
  [127,"Reproduction & Life Cycle","Baby elephants are called calves."],
  [128,"Reproduction & Life Cycle","Adult females are called cows, adult males are bulls, and sub-adults are calves."],
  [129,"Reproduction & Life Cycle","Elephants typically live 60–70 years in the wild."],
  [130,"Reproduction & Life Cycle","The oldest recorded elephant was Lin Wang, an Asian elephant who lived to 86 years old before dying in February 2003."],
  [131,"Reproduction & Life Cycle","In captivity, elephants typically live only about 40 years due to ailments from unnatural conditions."],
  [132,"Reproduction & Life Cycle","Captive elephants suffer from confinement-related arthritis, foot disease, and obesity."],
  [133,"Reproduction & Life Cycle","Male elephants experience musth — a period where testosterone levels increase by a factor of 60 or more, making them extremely aggressive."],
  [134,"Reproduction & Life Cycle","Musth can last up to 60 days in Asian elephants."],
  [135,"Reproduction & Life Cycle","During musth, bulls carry their heads and ears higher and produce a characteristic rumble."],
  [136,"Diet & Eating Habits","Elephants eat up to 300 pounds (136 kg) of vegetation per day."],
  [137,"Diet & Eating Habits","In human terms, an elephant's daily food intake is equivalent to eating 1,200 hamburgers."],
  [138,"Diet & Eating Habits","Wild adult elephants eat 220–440 pounds (100–200 kg) of food every day."],
  [139,"Diet & Eating Habits","An adult elephant consumes approximately 50 tonnes of food per year."],
  [140,"Diet & Eating Habits","Their diet includes grasses, leaves, branches, shrubs, fruit, seeds, bark, and roots."],
  [141,"Diet & Eating Habits","Asian elephants feed on more than 100 different species of plants."],
  [142,"Diet & Eating Habits","Elephants spend up to 16 hours a day collecting and eating food."],
  [143,"Diet & Eating Habits","Elephants are strict herbivores — they eat no meat."],
  [144,"Diet & Eating Habits","They can drink up to 60 gallons (227 liters) of water per day — equivalent to 1,120 cans of soda."],
  [145,"Diet & Eating Habits","An adult elephant needs about 210 liters (55 gallons) of water daily."],
  [146,"Diet & Eating Habits","The trunk can suction 10 liters of water at a time, then squirt it into the mouth."],
  [147,"Diet & Eating Habits","Elephants can go several days without water (desert elephants use fog absorption)."],
  [148,"Diet & Eating Habits","Their digestive system is relatively inefficient — they digest only about 40% of what they eat."],
  [149,"Diet & Eating Habits","Elephant dung enriches soil, supports plant growth, and provides a habitat for insects like dung beetles."],
  [150,"Diet & Eating Habits","90 different tree species rely on elephants for seed propagation through their dung."],
  [151,"Anatomy & Physiology","An elephant's outer skin layer is about 50 times as thick as a human's."],
  [152,"Anatomy & Physiology","Despite the thickness, their skin is highly sensitive, especially in the armpits, groin, behind the ears, and around the eyes."],
  [153,"Anatomy & Physiology","Elephants are the only mammals without a pleural cavity — their lungs are connected directly to the chest wall and diaphragm."],
  [154,"Anatomy & Physiology","This means if their lungs are constricted or there is too much pressure on the chest, they can suffocate."],
  [155,"Anatomy & Physiology","This unique lung structure allows elephants to withstand underwater pressure while using their trunk as a snorkel."],
  [156,"Anatomy & Physiology","Elephants' hearts have a double-pointed base, making them more circular than heart-shaped — shared only with sirenians (manatees and dugongs)."],
  [157,"Anatomy & Physiology","An elephant's heart beats only 28–30 times per minute (humans: 60–100 bpm)."],
  [158,"Anatomy & Physiology","Their heart rate actually speeds up slightly when they lie down because body weight reduces lung capacity."],
  [159,"Anatomy & Physiology","Elephants can get sunburned — they protect themselves with mud baths, dirt, and dust."],
  [160,"Anatomy & Physiology","Elephants have only four teeth at a time (one upper and one lower on each side)."],
  [161,"Anatomy & Physiology","The elephant's name 'Loxodonta' comes from Greek words meaning 'slanting tooth' — referring to the diamond shape of their molar enamel ridges."],
  [162,"Anatomy & Physiology","Elephants produce about 100 kg (220 lbs) of dung per day."],
  [163,"Anatomy & Physiology","An elephant's brain makes up about 0.08% of its total body weight, while a human's brain is about 2% of body weight."],
  [164,"Ears & Temperature Regulation","Elephant ears are roughly one-sixth the size of their entire body."],
  [165,"Ears & Temperature Regulation","African elephant ears can reach up to 6 feet (1.8 m) in length and weigh as much as 100 pounds (45 kg)."],
  [166,"Ears & Temperature Regulation","Asian elephant ears measure about 5 feet (1.5 m) and are smaller — adapted to cooler climates."],
  [167,"Ears & Temperature Regulation","The backs of elephant ears are packed with a dense network of blood vessels covered by thin skin."],
  [168,"Ears & Temperature Regulation","Flapping their ears pumps blood through these vessels, releasing heat and cooling the body by 3–5°C."],
  [169,"Ears & Temperature Regulation","Elephants can pump their entire blood volume through their ear vessels every 20 minutes."],
  [170,"Ears & Temperature Regulation","They can dilate their blood vessels to increase flow to the ears for more cooling."],
  [171,"Ears & Temperature Regulation","African elephant ears are shaped like the continent of Africa; Asian elephant ears are shaped like India."],
  [172,"Ears & Temperature Regulation","Each elephant's ear size and shape is as unique as a human fingerprint."],
  [173,"Ears & Temperature Regulation","Elephants also spray water or mud on the backs of their ears and spread them to face the wind for extra cooling."],
  [174,"Ears & Temperature Regulation","Elephants' only sweat glands are between their toes — they cannot sweat like humans."],
  [175,"Ears & Temperature Regulation","Beyond cooling, elephant ears play a role in funneling sound toward the inner ear and in visual communication (spreading ears = aggression or joy)."],
  [176,"Feet, Movement & Speed","Elephants actually walk on their tiptoes — behind their toes is a mass of soft tissue called a digital pad that acts as a shock absorber."],
  [177,"Feet, Movement & Speed","Despite weighing up to 7.5 tonnes, elephants are remarkably quiet walkers thanks to the cushioning pads."],
  [178,"Feet, Movement & Speed","Elephants can reach speeds of up to 25 mph (40 km/h) — faster than most humans can run."],
  [179,"Feet, Movement & Speed","Elephants can travel up to 120 miles (193 km) in a single day when necessary."],
  [180,"Feet, Movement & Speed","In the wild, elephants migrate up to 30 miles (48 km) daily and are active for about 18 hours a day."],
  [181,"Feet, Movement & Speed","Desert elephants can walk up to 62–93 miles (100–150 km) per day to find food and water."],
  [182,"Feet, Movement & Speed","While elephants can move forward and backward, they cannot technically run — they are too heavy to lift all four legs off the ground simultaneously."],
  [183,"Feet, Movement & Speed","The 'running' elephants do is actually a fast walk where at least one foot stays on the ground at all times."],
  [184,"Feet, Movement & Speed","Elephants are natural swimmers and love being in water."],
  [185,"Feet, Movement & Speed","An elephant's large footprints can create small pools of water that become lifelines for smaller creatures."],
  [186,"Feet, Movement & Speed","Elephants have a different number of toenails by species: African savanna elephants have 4 front / 3 rear; forest elephants and Asian elephants have 5 front / 4 rear."],
  [187,"Skin, Hair & Appearance","Despite appearing hairless, elephants have sparse hair distributed unevenly across their bodies."],
  [188,"Skin, Hair & Appearance","The most noticeable hair concentrations are on the top of the head, trunk, and tail."],
  [189,"Skin, Hair & Appearance","Unlike most mammals, elephants' hair keeps them cool rather than warm — the pin-shaped hairs act as cooling fins to dissipate heat."],
  [190,"Skin, Hair & Appearance","Tail hair can reach lengths of up to 3 feet (1 m) and is composed of keratin (different from body hair)."],
  [191,"Skin, Hair & Appearance","Tail hair grows in parallel rows and is primarily used to slap away flies and insects."],
  [192,"Skin, Hair & Appearance","Baby elephants have more hair than adults, and Asian elephants have more hair than African elephants."],
  [193,"Skin, Hair & Appearance","Baby Asian elephants have the most hair — it is dark reddish-brown in color."],
  [194,"Skin, Hair & Appearance","An elephant's skin is grayish to brown, but can appear reddish-brown after dust or mud baths."],
  [195,"Skin, Hair & Appearance","Wrinkled skin helps elephants trap moisture in the folds while allowing excess heat to escape."],
  [196,"Skin, Hair & Appearance","Elephants' hair at the end of their trunks is super-sensitive, almost like a cat's whiskers, used to locate food and detect nearby herd members."],
  [197,"Skin, Hair & Appearance","Each elephant's hair is unique from individual to individual, much like human hair."],
  [198,"Elephants vs. Other Animals","An African elephant weighs about 20 times more than an adult lion (~190 kg)."],
  [199,"Elephants vs. Other Animals","An elephant weighs more than 130 adult humans."],
  [200,"Elephants vs. Other Animals","An elephant weighs roughly 8 times more than a giraffe (~800 kg)."],
  [201,"Elephants vs. Other Animals","An elephant weighs about 4 times more than a hippopotamus (~1,500 kg)."],
  [202,"Elephants vs. Other Animals","An elephant weighs approximately 6 times more than a black rhinoceros (~1,000 kg)."],
  [203,"Elephants vs. Other Animals","An elephant's brain is larger than any other land animal's brain, but a sperm whale's brain is about 5 times larger (~7.8 kg)."],
  [204,"Elephants vs. Other Animals","An elephant's heart weighs about 15 times more than a human heart (~300 g)."],
  [205,"Elephants vs. Other Animals","An elephant's heart beats half as fast as a human heart at rest."],
  [206,"Elephants vs. Other Animals","An elephant eats about 30 times more food per day than an adult human (5 kg/day for humans vs. 150 kg for elephants)."],
  [207,"Elephants vs. Other Animals","An elephant drinks about 50 times more water per day than the average human (2 liters/day for humans vs. 100 liters for elephants)."],
  [208,"Elephants vs. Other Animals","The elephant's 22-month pregnancy is nearly 3 times longer than a human's (9 months)."],
  [209,"Elephants vs. Other Animals","An elephant's trunk has about 67 times more muscles than the entire human body."],
  [210,"Elephants vs. Other Animals","An elephant's lifespan of 60–70 years is comparable to an average human lifespan (73 years globally)."],
  [211,"Elephants vs. Other Animals","Elephants are about 3 times taller at the shoulder than the average adult human (1.7 m)."],
  [212,"Elephants vs. Other Animals","An elephant weighs roughly 100 times more than a large dog (Labrador Retriever ~35 kg)."],
  [213,"Elephants vs. Other Animals","An elephant can run at 25 mph — about 3.5 times faster than the average human jogging speed."],
  [214,"Mammoths & Prehistoric Elephants","Mammoths (genus Mammuthus) are extinct relatives of modern elephants, found as fossils on every continent except Australia and South America."],
  [215,"Mammoths & Prehistoric Elephants","The woolly mammoth (Mammuthus primigenius) is the best-known mammoth species."],
  [216,"Mammoths & Prehistoric Elephants","Woolly mammoths had a yellowish-brown undercoat about 2.5 cm (1 inch) thick beneath dark brown outer hair up to 50 cm (20 inches) long."],
  [217,"Mammoths & Prehistoric Elephants","Under their extremely thick skin, mammoths had a layer of fat up to 8 cm (3 inches) thick for insulation."],
  [218,"Mammoths & Prehistoric Elephants","The North American imperial mammoth reached a shoulder height of 4 meters (14 feet) — even larger than the biggest modern elephants."],
  [219,"Mammoths & Prehistoric Elephants","Mammoth skulls were high and domelike, unlike the flatter skulls of modern elephants."],
  [220,"Mammoths & Prehistoric Elephants","Mammoth ears were smaller than modern elephants' — an adaptation to cold climates that reduced heat loss."],
  [221,"Mammoths & Prehistoric Elephants","Cave paintings show mammoths had a mound of fat as a hump on their back, which does not survive in fossil remains."],
  [222,"Mammoths & Prehistoric Elephants","Mammoth tusks were very long and directed downward, sometimes curving over each other in older males."],
  [223,"Mammoths & Prehistoric Elephants","Woolly mammoths were largely extinct about 10,000 years ago."],
  [224,"Mammoths & Prehistoric Elephants","A tiny population of mammoths survived on Wrangel Island (Arctic Russia) until just 4,300 years ago — when the Egyptian pyramids were already ancient."],
  [225,"Mammoths & Prehistoric Elephants","The last Wrangel Island mammoths died out from inbreeding and loss of genetic diversity."],
  [226,"Mammoths & Prehistoric Elephants","Fossil mammoth ivory was so abundant it was exported from Siberia to China and Europe since medieval times."],
  [227,"Mammoths & Prehistoric Elephants","In some cases, sled dogs were fed meat from frozen mammoth carcasses preserved in ice for nearly 30,000 years."],
  [228,"Mammoths & Prehistoric Elephants","The oldest preserved mammoth DNA — also the oldest known animal DNA — dates to more than one million years ago."],
  [229,"Mammoths & Prehistoric Elephants","Mammoths had alternating plates of enamel and dentine in their teeth, worn down by constant back-to-front chewing."],
  [230,"Mammoths & Prehistoric Elephants","Remains of arctic plants have been found in frozen mammoth digestive tracts."],
  [231,"Mammoths & Prehistoric Elephants","Mammoths were clearly hunted by early humans — evidence exists in tool marks on bones and cave paintings."],
  [232,"Mammoths & Prehistoric Elephants","Small populations of woolly mammoths may have survived in North America until 7,600–10,500 years ago."],
  [233,"Mammoths & Prehistoric Elephants","The closest living relatives of elephants are hyraxes, manatees, and dugongs — all members of the clade Paenungulata."],
  [234,"Mammoths & Prehistoric Elephants","Dwarf mammoth species evolved on various islands where normal-sized mammoths became isolated and shrank over generations."],
  [235,"Mammoths & Prehistoric Elephants","Ancient elephant ancestors, over millions of years, gradually evolved from small, pig-like creatures to the giants we know today."],
  [236,"Human Deaths & Danger","Elephants kill approximately 500 humans per year worldwide."],
  [237,"Human Deaths & Danger","For comparison, hippopotamuses kill about 500 people per year as well."],
  [238,"Human Deaths & Danger","Mosquitoes kill approximately 725,000–1,000,000 people per year — making them by far the deadliest animal to humans."],
  [239,"Human Deaths & Danger","Crocodiles kill about 1,000 people per year."],
  [240,"Human Deaths & Danger","Lions kill approximately 250 people per year."],
  [241,"Human Deaths & Danger","Sharks kill about 5–10 humans per year — meaning elephants kill 50–100 times more people than sharks."],
  [242,"Human Deaths & Danger","Despite being herbivores with no natural predators, elephants are among the top 10 deadliest large animals to humans."],
  [243,"Human Deaths & Danger","Human-elephant conflict is a major conservation issue, especially in Asia and Africa where expanding human settlements encroach on elephant territories."],
  [244,"Human Deaths & Danger","More humans are killed by elephants each year than by wolves, bears, or alligators."],
  [245,"Human Deaths & Danger","Elephants in musth (extreme testosterone surge) are the most dangerous to humans."],
  [246,"Human Deaths & Danger","Elephants have been documented destroying entire villages during violent encounters."],
  [247,"Human Deaths & Danger","Despite the danger, humans kill vastly more elephants — approximately 100 elephants per day for their ivory."],
  [248,"Conservation & Poaching","In 1979, there were 1.3 million elephants in Africa; today there are approximately 400,000."],
  [249,"Conservation & Poaching","Over 90% of African elephants have been killed in the last century."],
  [250,"Conservation & Poaching","The WWF estimates that around 100 elephants are killed every single day for their ivory."],
  [251,"Conservation & Poaching","Three modern elephant species exist today: the African savanna elephant, African forest elephant, and Asian elephant."],
  [252,"Conservation & Poaching","African savanna elephants and Asian elephants are listed as Endangered on the IUCN Red List."],
  [253,"Conservation & Poaching","African forest elephants are listed as Critically Endangered."],
  [254,"Conservation & Poaching","African savanna and forest elephants diverged genetically over 3 million years ago."],
  [255,"Conservation & Poaching","Only about 30,000–50,000 Asian elephants remain in the wild."],
  [256,"Conservation & Poaching","There are three subspecies of Asian elephant: Indian, Sri Lankan, and Sumatran."],
  [257,"Conservation & Poaching","Only 2,400–2,800 Sumatran elephants remain — the smallest and most endangered subspecies."],
  [258,"Conservation & Poaching","Sri Lanka has the highest density of elephants in Asia, with about 7,500 wild elephants."],
  [259,"Conservation & Poaching","The Indian elephant is the most widespread subspecies, with 20,000–30,000 remaining."],
  [260,"Conservation & Poaching","Over 1,000 Mali elephants once roamed West Africa; now there are fewer than 400."],
  [261,"Conservation & Poaching","16 countries have banned the use of elephants in circuses due to premature deaths from captivity."],
  [262,"Conservation & Poaching","Poachers have created an evolutionary arms race — elephants in heavily poached areas are increasingly born tuskless."],
  [263,"History, Culture & Mythology","Hindus worship Ganesha, the elephant-headed god of wisdom, success, and good luck."],
  [264,"History, Culture & Mythology","Thomas Edison electrocuted an elephant named Topsy in 1903 to 'prove' that Tesla's AC current was dangerous — it was the first filmed animal death in history."],
  [265,"History, Culture & Mythology","Topsy's owners had initially planned to hang her before Edison's intervention."],
  [266,"History, Culture & Mythology","Black Ivory Coffee, at $50 per serving or $500 per pound, is the world's most expensive coffee — made from beans eaten and excreted by elephants."],
  [267,"History, Culture & Mythology","Elephants appeared in ancient Roman arenas and were used in warfare by Hannibal, who famously crossed the Alps with war elephants in 218 BC."],
  [268,"History, Culture & Mythology","Alexander the Great encountered war elephants in India during his campaigns in 326 BC."],
  [269,"History, Culture & Mythology","The word 'elephant' comes from the Greek 'elephas' meaning ivory, which in turn comes from a Phoenician word."],
  [270,"History, Culture & Mythology","The scientific name of the African elephant genus, Loxodonta, means 'slanting tooth'."],
  [271,"History, Culture & Mythology","Elephants were depicted in Paleolithic cave art in Europe, showing realistic herds of mammoths."],
  [272,"History, Culture & Mythology","Cave dwellers in Europe realistically depicted mammoth herds in their artwork, providing valuable information about prehistoric elephant behavior."],
  [273,"History, Culture & Mythology","The elephant is the national animal of Thailand and appears on the country's royal flag historically."],
  [274,"History, Culture & Mythology","'White elephants' are considered sacred in some Southeast Asian cultures — the phrase 'white elephant' comes from Thai kings gifting rare albino elephants that could not be put to work but had to be maintained at great cost."],
  [275,"Weird, Wild & Unexpected Facts","Despite appearing to cry, elephants cannot actually cry — they do not have tear ducts. Fluid from their eyes simply runs down their cheeks."],
  [276,"Weird, Wild & Unexpected Facts","Elephants are terrified of bees and ants — some African farmers line fields with beehives as a natural elephant repellant."],
  [277,"Weird, Wild & Unexpected Facts","An elephant can sense a fly landing on its skin despite the 1-inch-thick hide."],
  [278,"Weird, Wild & Unexpected Facts","Elephants cannot jump — they are the only mammal that cannot."],
  [279,"Weird, Wild & Unexpected Facts","Elephants sleep standing up most of the time, but occasionally lie down for short periods."],
  [280,"Weird, Wild & Unexpected Facts","The pharyngeal pouch behind an elephant's tongue may also be used as a reservoir for water, allowing elephants to spray themselves even when no water source is nearby."],
  [281,"Weird, Wild & Unexpected Facts","Elephants have been documented using tools — holding branches to scratch themselves and wielding sticks."],
  [282,"Weird, Wild & Unexpected Facts","Mali elephants migrate farther than any other elephant type — traveling 280–435 miles per year."],
  [283,"Weird, Wild & Unexpected Facts","Desert elephants in the Namib Desert (the world's oldest desert) survive temperatures up to 122°F (50°C) with only 1–4 inches of annual rainfall."],
  [284,"Weird, Wild & Unexpected Facts","Desert elephants have developed thinner bodies and wider feet for walking on sand."],
  [285,"Weird, Wild & Unexpected Facts","Desert elephants roam primarily at night to avoid extreme heat."],
  [286,"Weird, Wild & Unexpected Facts","Elephant hair is like a built-in cooling fin system — a physics discovery that inspired engineers to develop better heat-transfer systems."],
  [287,"Weird, Wild & Unexpected Facts","Elephants use infrasonic communication that travels through the ground at speeds faster than sound through air."],
  [288,"Weird, Wild & Unexpected Facts","An elephant's trunk is so strong it can pull down a full tree, yet delicate enough to pick up a single coin from a flat surface."],
  [289,"Weird, Wild & Unexpected Facts","Some elephants have been observed creating 'art' by holding brushes with their trunks."],
  [290,"Weird, Wild & Unexpected Facts","Elephants play an irreplaceable role in climate regulation — by maintaining forest and savanna ecosystems, they help sustain trees and plants that absorb CO2."],
  [291,"Weird, Wild & Unexpected Facts","During dry seasons, elephants use their tusks to dig water holes that provide water for dozens of other species."],
  [292,"Weird, Wild & Unexpected Facts","Elephant footprints create micro-ecosystems — small pools that frogs, insects, and birds depend on."],
  [293,"Weird, Wild & Unexpected Facts","Elephants can hold grudges for decades against specific humans who harmed them."],
  [294,"Weird, Wild & Unexpected Facts","A group of elephants is called a 'herd' or sometimes a 'parade'."],
  [295,"Weird, Wild & Unexpected Facts","The elephant's closest living relatives are the tiny, rabbit-like hyrax — it's hard to imagine a more unlikely cousin."],
  [296,"Weird, Wild & Unexpected Facts","Elephants can distinguish between human languages and genders — studies show they react defensively to the voices of Maasai men (who historically hunt them) but not to the voices of Maasai women or Kamba farmers."],
  [297,"Weird, Wild & Unexpected Facts","Elephants have been observed covering dead humans with branches and leaves, not just other elephants."],
  [298,"Weird, Wild & Unexpected Facts","An elephant's stomach can hold up to 100 liters (26 gallons) of food and water."],
  [299,"Weird, Wild & Unexpected Facts","Elephants in captivity sometimes develop obsessive-compulsive behaviors like swaying back and forth — a sign of psychological distress from confinement."],
  [300,"Weird, Wild & Unexpected Facts","Baby elephants sometimes trip over their own trunks because they haven't learned to control them yet."],
];

export async function POST() {
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  if (!serviceKey || !url) {
    return NextResponse.json({ error: "Missing env vars" }, { status: 500 });
  }

  const admin = createClient(url, serviceKey, { auth: { persistSession: false } });

  // Insert all 300 facts (table must already exist — create it via Supabase dashboard SQL editor first)
  const rows = FACTS.map(([fact_number, category, content]) => ({
    fact_number,
    category,
    content,
  }));

  const BATCH = 50;
  const results: Array<{ batch: number; inserted: number; error?: string }> = [];

  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH);
    const { error, count } = await admin
      .from("elephant_facts")
      .insert(batch, { count: "exact" });
    results.push({
      batch: Math.floor(i / BATCH) + 1,
      inserted: error ? 0 : (count ?? batch.length),
      error: error?.message,
    });
  }

  const totalInserted = results.reduce((s, r) => s + r.inserted, 0);
  const errors = results.filter((r) => r.error);

  return NextResponse.json({
    totalInserted,
    batches: results.length,
    errors: errors.length ? errors : undefined,
  });
}
