/**
 * Static mock for Storybook/tests. Live choropleth uses `fetchHeatmapData()`
 * (regions + population_estimates + species + migration_corridors + threat_incidents).
 */
import type { MapCountryMetric } from "./types";

export const heatmapData: MapCountryMetric[] = [
  {
    country: "Kenya",
    isoCode: "KEN",
    coordinates: [0.1769, 37.9083],
    geometryRef: "ISO-KEN",
    population: 36250,
    elephantType: "AfricanSavanna",
    lifeExpectancy: 64,
    poachingRate: 4.2,
  },
  {
    country: "Tanzania",
    isoCode: "TZA",
    coordinates: [-6.369, 34.8888],
    geometryRef: "ISO-TZA",
    population: 41500,
    elephantType: "AfricanSavanna",
    lifeExpectancy: 63,
    poachingRate: 5.8,
  },
  {
    country: "Botswana",
    isoCode: "BWA",
    coordinates: [-22.3285, 24.6849],
    geometryRef: "ISO-BWA",
    population: 130000,
    elephantType: "AfricanSavanna",
    lifeExpectancy: 65,
    poachingRate: 1.1,
  },
  {
    country: "Zimbabwe",
    isoCode: "ZWE",
    coordinates: [-19.0154, 29.1549],
    geometryRef: "ISO-ZWE",
    population: 83000,
    elephantType: "AfricanSavanna",
    lifeExpectancy: 62,
    poachingRate: 3.5,
  },
  {
    country: "South Africa",
    isoCode: "ZAF",
    coordinates: [-30.5595, 22.9375],
    geometryRef: "ISO-ZAF",
    population: 27000,
    elephantType: "Mixed",
    lifeExpectancy: 61,
    poachingRate: 2.4,
  },
  {
    country: "Namibia",
    isoCode: "NAM",
    coordinates: [-22.9576, 18.4904],
    geometryRef: "ISO-NAM",
    population: 24000,
    elephantType: "AfricanSavanna",
    lifeExpectancy: 63,
    poachingRate: 1.8,
  },
  {
    country: "Gabon",
    isoCode: "GAB",
    coordinates: [-0.8037, 11.6094],
    geometryRef: "ISO-GAB",
    population: 95000,
    elephantType: "AfricanForest",
    lifeExpectancy: 60,
    poachingRate: 6.2,
  },
  {
    country: "India",
    isoCode: "IND",
    coordinates: [20.5937, 78.9629],
    geometryRef: "ISO-IND",
    population: 27000,
    elephantType: "Asian",
    lifeExpectancy: 58,
    poachingRate: 3.1,
  },
  {
    country: "Sri Lanka",
    isoCode: "LKA",
    coordinates: [7.8731, 80.7718],
    geometryRef: "ISO-LKA",
    population: 7000,
    elephantType: "Asian",
    lifeExpectancy: 59,
    poachingRate: 2.0,
  },
];
